In [95]:
# Write a Python program to print the NumPy version in your system.
import numpy as np
print(np.version.version)
np.__version__


1.19.2


'1.19.2'

In [51]:
# Write a Python program to reverse an array (first element becomes last).
arr1 = np.arange(10).reshape((5,2))
print(arr1)

arr_rev = np.flip(arr1, axis = 0)
arr_rev

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


array([[8, 9],
       [6, 7],
       [4, 5],
       [2, 3],
       [0, 1]])

In [37]:
# Write a Python program to convert a list and tuple into arrays.

def convert_list_to_array(a_list):
    return np.array(a_list)

l1 = [1,1,3,3,10,10]
print(convert_list_to_array(l1))

def convert_tuple_to_array(a_tuple):
    return np.array(a_tuple)

tuple_1 = (2,2,3,3,12,12)
print(convert_tuple_to_array(tuple_1))

[ 1  1  3  3 10 10]
[ 2  2  3  3 12 12]


In [32]:
# Write a Python program to find common values between two arrays.
arr1 = np.arange(5,31,5)
arr2 = np.arange(10,51,10)

print(arr1)
print(arr2)

common_values = np.intersect1d(arr1, arr2)
print(common_values)

[ 5 10 15 20 25 30]
[10 20 30 40 50]
[10 20 30]


In [34]:
# Write a Python program compare two arrays using numpy.
arr1 = np.arange(2,11,2)
arr2 = np.array([2,4,6,8,10])

print((arr1 == arr2).all())

print(np.array_equal(arr1,arr2))

True
True


In [83]:
# Write a Python program to change the dimension of an array.
import numpy as np

arr1 = np.arange(1,16)
print(arr1)
print(np.ndim(arr1))

arr1 = np.reshape(arr1, (3,5))
print(arr1)
print(np.ndim(arr1))

print(np.shape(arr1))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
1
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
2
(3, 5)


In [7]:
# Write a Python program (using numpy) to sum of all the multiples of 3 or 5 below 100.
import numpy as np
a3 = np.arange(3,100,3)
a5 = np.arange(5,100,5)

#print(a3)
#print(a5)

common_list = list(a3)

# removing the common multiples in the two arrays
for i in a5:
    if i not in a3:
        common_list.append(i)

# converting the list of multiples into an array
cl_array = np.array(common_list)
#print(cl_array)

# using numpy sum function to get the sum of all multiples of 3 or 5 below 100
sum_of_multiples = np.sum(cl_array)
print(sum_of_multiples)
        


[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]
[ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99  5 10 20 25 35 40 50 55 65 70 80 85 95]
2318


In [14]:
# Write a Python program to convert a NumPy array into Python list structure. 

arr1 = np.array([[1,2,3], [5,6,7], [1,2,1]])
np.ndim(arr1)

type(arr1)

l_arr1 = list(arr1)
type(l_arr1)
print(l_arr1)

[array([1, 2, 3]), array([5, 6, 7]), array([1, 2, 1])]


In [80]:
# Write a Python program to how to add an extra column to a numpy array.
# https://thispointer.com/how-to-add-columns-to-numpy-array-in-python/

arr1 = np.array([[1,2,3], [2,4,6], [3,6,9], [4,8,12]])
arr3 = np.insert(arr1, 3, [9, 9, 9,9], axis = 1)
arr3

array([[ 1,  2,  3,  9],
       [ 2,  4,  6,  9],
       [ 3,  6,  9,  9],
       [ 4,  8, 12,  9]])

In [90]:
# Write a Python program to check whether the numpy array is empty or not.
arr1 = np.arange(10)
arr2 = np.array([])

if len(arr2) != 0:
    print("Not empty")
else:
    print("Empty")

Empty


In [94]:
# Write a Python program to normalize a 3x3 random matrix.
arr1 = np.array([[1,2,3], [2,4,6], [3,6,9]])


In [ ]:
# How to ignore all numpy warnings (not recommended)?

In [72]:
# How to swap two rows of an array?
arr1 = np.array([[1,2,3], [2,4,6], [3,6,9], [4,8,12]])
print(arr1)
arr1[[0,3] ] = arr1[[3,0] ] 
arr1

[[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]]


array([[ 4,  8, 12],
       [ 2,  4,  6],
       [ 3,  6,  9],
       [ 1,  2,  3]])

In [19]:
# Python program to create a random vector of size 10 and sort it.
rand_arr = np.random.rand(10)
np.sort(rand_arr)

array([0.08022659, 0.09337749, 0.12900649, 0.28158794, 0.45278314,
       0.45917021, 0.48648731, 0.57545267, 0.65770823, 0.91323879])

In [23]:
# Write a Python program to check two random arrays are equal or not.
rand_arr1 = np.random.rand(10)
rand_arr2 = np.random.rand(10)
# for i in rand_arr1:
#     if rand_arr1[i] == rand_arr[i]:
#         print("equal")
#     else:
#         print("not equal")
    
print(rand_arr1)
print(rand_arr2)

[0.93639013 0.64656825 0.78503264 0.14040873 0.87917394 0.27596025
 0.65847694 0.07779479 0.06738152 0.94011059]
[0.25460784 0.6471094  0.95226795 0.25854471 0.86400562 0.97326005
 0.0257896  0.98480833 0.23082667 0.26210606]


In [28]:
# Write a Python program to add, subtract, multiply, divide arguments element-wise.
arr1 = np.full((3,3), 10)
arr2 = np.full((3,3), 2)

print(arr1)
print(arr2)
print()

add_array = np.add(arr1, arr2)
subtract_array = np.subtract(arr1, arr2)
multiply_array = np.multiply(arr1, arr2)
divide_array  = np.divide(arr1, arr2)

print(f' arr1 + arr2: {add_array}')
print(f' arr1 - arr2: {subtract_array}')
print(f' arr1 * arr2:{multiply_array}')
print(f' arr1 / arr2: {divide_array}')



[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]

 arr1 + arr2: [[12 12 12]
 [12 12 12]
 [12 12 12]]
 arr1 - arr2: [[8 8 8]
 [8 8 8]
 [8 8 8]]
 arr1 * arr2:[[20 20 20]
 [20 20 20]
 [20 20 20]]
 arr1 / arr2: [[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [63]:
# Write a Python program to get the dates of yesterday, today and tomorrow.

# In NumPy with the help of NumPy.datetime64(‘today’, ‘D’), we will find today date 
# and if we want some date before today then we will subtract the no-of-date with the 
# help of np.timedelta64() from today. And if we want some date after today then we will 
# add the no of date with the help of np.timedelta64() from today. 
# For yesterday, we will subtract 1 date, for tomorrow we will add 1 date.

today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1)
yesterday = np.datetime64('today') - np.timedelta64(1)

print(f'yesterday: {yesterday}')
print(f'today: {today}')
print(f'tomorrow: {tomorrow}')


#help(np.datetime64())

yesterday: 2022-06-22
today: 2022-06-23
tomorrow: 2022-06-24
